stages:
  - test
  - deploy

variables:
  TESTVAR:
    value: "mkdir testvardir"

test:
  stage: "test"
  image: python:3.8
  script:
    - pip install requirements.txt
    - python -m pytest --verbose

deploy:
  stage: "deploy"
  image: jenkins/ssh-slave
  before_script:
    # runners needs ssh installed to use ssh....................whowouldvethought........
    # decode ssh_key because gitlab no like whitespace
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
    # git cloned using http to prevent authorization flags
  script:
    # code has to be within ssh quotes to run on production server, otherwise runs on runner
    # ssh commands put in $remote_script varible
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no app@10.8.156.76 'bash -s' "cd ./connectnow && killall python3; git pull; python3 -m flask --app project/app.py run --host=0.0.0.0 >> log.txt 2>> error.txt &"
    #variable test no work yet
    #- $TESTVAR