stages:
  - deploy
variables:
  TESTVAR:
    value: "echo 'test' > testvar.txt"
deploy:
  stage: "deploy"
  image: jenkins/ssh-slave
  before_script:
    - apt-get update
    # runners needs ssh installed to use ssh....................whowouldvethought........
    #- apt-get install openssh-client -y
    # decode ssh_key because gitlab no like whitespace
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
    # git cloned using http to prevent authorization flags
  script:
    # code has to be within ssh quotes to run on production server, otherwise runs on runner
    # ssh commands put in $remote_script varible
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no app@10.8.156.76 'bash -s' < $remote_script
    - $TESTVAR