stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building your project here"

test:
  stage: test
  script:
    - echo "Running tests"

deploy:
  stage: deploy
  script:
    - git checkout main
    - git pull origin main
    - echo "Deploying to production"
