stages:
  - deploy

deploy:
  stage: "deploy"
  before_script:
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
  script:
    # code has to be in ssh quotes to run on production server
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no app@10.8.156.76 "wall doodoo"