stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sudo apt-get install git -y

deploy:
  stage: "deploy"
  image: "jenkins/ssh-slave"
  before_script:
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
  script:
    - echo "restarting server"
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no app@10.8.156.76 "cd connectnow&&killall python3;python3 -m flask --app project/app.py run --host=0.0.0.0 >> log.txt 2>>error.txt &"