stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building your project here"
    - apt-get update -y
    - apt-get upgrade -y
    - apt-get install python python3-pip -y
    - pip3 install -r requirements.txt
    - python3 create_db.py



test:
  stage: test
  script:
    - echo "Running tests"

deploy:
  stage: deploy
  script:
    - git checkout main
    - git pull origin main
    - echo "Deploying to production"
