stages:
  - deploy

deploy:
  stage: "deploy"
  before_script:
    - apt-get update
    - apt-get install -y git python3 python3-pip
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
    - hostname
  script:
    - echo "pulling gitlab"
    - git pull http://10.8.158.167:8888/lothar243/connectnow.git