stages:
  - example_job
  - deploy

example_job:
  stage: "deploy"
  image: "jenkins/ssh-slave"
  before_script:
    - echo -n $ssh_key | base64 -d > SSH_KEY_FILE
    - chmod 400 SSH_KEY_FILE
  script:
    - ssh -i SSH_KEY_FILE -o StrictHostKeyChecking=no app@10.8.156.76 "cd connectnow&&killall python3;python3 -m flask --app project/app.py run --host=0.0.0.0 >> log.txt 2>>error.txt &"

deploy:
  stage: deploy
  script:
    - echo "test"
    - cd /home/app/connectnow
    - git checkout main
    - git pull 
